sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jk0517/docker-react -f  Dockerfile.dev .

script:
  - docker run -e CI=true jk0517/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-741171319322'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
